#!/bin/bash
echo "[Phase 1 Verification]"
echo "→ Checking Tailwind setup"
grep -q "@tailwind base" ./src/app/globals.css && echo "✅ Tailwind base ok"
echo "→ Checking layout.tsx"
test -f ./src/app/layout.tsx && echo "✅ layout.tsx found"
echo "→ Checking homepage"
test -f ./src/app/page.tsx && echo "✅ Homepage found"
echo "→ Checking auth pages"
test -f ./src/app/'(auth)'/login/page.tsx && echo "✅ Login page found"
test -f ./src/app/'(auth)'/register/page.tsx && echo "✅ Register page found"
echo "→ Checking Prisma schema"
test -f ./prisma/schema.prisma && echo "✅ Prisma schema found"
echo "→ Checking SQL files"
test -f ./sql/init.sql && echo "✅ init.sql found"
test -f ./sql/users.sql && echo "✅ users.sql found"
echo "Verification complete."
